local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("cpp", {
  -- tourist-style boilerplate (#define int long long, signed main)
  s("!t", {
    t({
      "#include <bits/stdc++.h>",
      "using namespace std;",
      "",
      "#define int long long",
      "",
      "void solve() {",
    }),
    i(1),
    t({
      "}",
      "",
      "signed main() {",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "    solve();",
      "}",
    }),
  }),

  -- jiangly-style boilerplate (i64, clean, minimal)
  s("!j", {
    t({
      "#include <bits/stdc++.h>",
      "using namespace std;",
      "",
      "using i64 = long long;",
      "",
      "void solve() {",
    }),
    i(1),
    t({
      "}",
      "",
      "int main() {",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "    solve();",
      "}",
    }),
  }),

  -- standard boilerplate with multiple test cases
  s("!tcs", {
    t({
      "#include <bits/stdc++.h>",
      "using namespace std;",
      "",
      "#define int long long",
      "",
      "void solve() {",
    }),
    i(1),
    t({
      "}",
      "",
      "signed main() {",
      "    ios::sync_with_stdio(false);",
      "    cin.tie(nullptr);",
      "    int t = 1;",
      "    cin >> t;",
      "    while (t--) solve();",
      "}",
    }),
  }),

  -- DSU (jiangly style)
  s("dsu", {
    t({
      "struct DSU {",
      "    vector<int> p;",
      "    DSU(int n) : p(n) { iota(p.begin(), p.end(), 0); }",
      "",
      "    int find(int x) {",
      "        while (x != p[x]) x = p[x] = p[p[x]];",
      "        return x;",
      "    }",
      "",
      "    bool unite(int a, int b) {",
      "        a = find(a), b = find(b);",
      "        if (a == b) return false;",
      "        p[b] = a;",
      "        return true;",
      "    }",
      "};",
    }),
  }),

  -- Fenwick tree (jiangly style)
  s("fenwick", {
    t({
      "template <typename T>",
      "struct Fenwick {",
      "    int n;",
      "    vector<T> a;",
      "    Fenwick(int n) : n(n), a(n) {}",
      "    void add(int x, T v) {",
      "        for (int i = x + 1; i <= n; i += i & -i) a[i - 1] += v;",
      "    }",
      "    T sum(int x) {",
      "        T res = 0;",
      "        for (int i = x; i > 0; i -= i & -i) res += a[i - 1];",
      "        return res;",
      "    }",
      "    T range(int l, int r) { return sum(r) - sum(l); }",
      "};",
    }),
  }),

  -- Segment tree (jiangly style)
  s("segtree", {
    t({
      "template <class Info>",
      "struct SegTree {",
      "    int n;",
      "    vector<Info> info;",
      "    SegTree(int n) : n(n), info(4 << __lg(n)) {}",
      "    SegTree(vector<Info> init) : SegTree(init.size()) {",
      "        function<void(int,int,int)> build = [&](int p, int l, int r) {",
      "            if (r - l == 1) { info[p] = init[l]; return; }",
      "            int m = (l + r) / 2;",
      "            build(2 * p, l, m);",
      "            build(2 * p + 1, m, r);",
      "            pull(p);",
      "        };",
      "        build(1, 0, n);",
      "    }",
      "    void pull(int p) { info[p] = info[2 * p] + info[2 * p + 1]; }",
      "    void modify(int p, int l, int r, int x, const Info &v) {",
      "        if (r - l == 1) { info[p] = v; return; }",
      "        int m = (l + r) / 2;",
      "        if (x < m) modify(2 * p, l, m, x, v);",
      "        else modify(2 * p + 1, m, r, x, v);",
      "        pull(p);",
      "    }",
      "    void modify(int x, const Info &v) { modify(1, 0, n, x, v); }",
      "    Info query(int p, int l, int r, int x, int y) {",
      "        if (l >= y || r <= x) return Info();",
      "        if (l >= x && r <= y) return info[p];",
      "        int m = (l + r) / 2;",
      "        return query(2 * p, l, m, x, y) + query(2 * p + 1, m, r, x, y);",
      "    }",
      "    Info query(int l, int r) { return query(1, 0, n, l, r); }",
      "};",
      "",
      "struct Info {",
      "    int sum;",
      "    Info(int sum = 0) : sum(sum) {}",
      "    friend Info operator+(const Info &a, const Info &b) {",
      "        return Info(a.sum + b.sum);",
      "    }",
      "};",
    }),
  }),

  -- Dijkstra (jiangly style)
  s("dijkstra", {
    t({
      "using i64 = long long;",
      "",
      "vector<i64> dijkstra(const vector<vector<pair<int, i64>>> &g, int s) {",
      "    int n = g.size();",
      "    vector<i64> d(n, 1e18);",
      "    priority_queue<pair<i64, int>, vector<pair<i64, int>>, greater<>> pq;",
      "    d[s] = 0;",
      "    pq.emplace(0, s);",
      "    while (!pq.empty()) {",
      "        auto [dist, u] = pq.top(); pq.pop();",
      "        if (dist != d[u]) continue;",
      "        for (auto [v, w] : g[u]) {",
      "            if (d[v] > d[u] + w) {",
      "                d[v] = d[u] + w;",
      "                pq.emplace(d[v], v);",
      "            }",
      "        }",
      "    }",
      "    return d;",
      "}",
    }),
  }),

  -- Modular int (jiangly style)
  s("mint", {
    t({
      "template <int MOD>",
      "struct Mint {",
      "    int v;",
      "    Mint() : v(0) {}",
      "    Mint(long long v_) : v(v_ % MOD) { if (v < 0) v += MOD; }",
      "    explicit operator int() const { return v; }",
      "    friend Mint operator+(Mint a, Mint b) { return (a.v += b.v) >= MOD ? a.v - MOD : a.v; }",
      "    friend Mint operator-(Mint a, Mint b) { return (a.v -= b.v) < 0 ? a.v + MOD : a.v; }",
      "    friend Mint operator*(Mint a, Mint b) { return Mint(1LL * a.v * b.v); }",
      "    friend Mint operator/(Mint a, Mint b) { return a * b.inv(); }",
      "    Mint &operator+=(Mint o) { return *this = *this + o; }",
      "    Mint &operator-=(Mint o) { return *this = *this - o; }",
      "    Mint &operator*=(Mint o) { return *this = *this * o; }",
      "    Mint pow(long long b) const {",
      "        Mint a = *this, r = 1;",
      "        for (; b; b >>= 1, a = a * a) if (b & 1) r = r * a;",
      "        return r;",
      "    }",
      "    Mint inv() const { return pow(MOD - 2); }",
      "    friend ostream &operator<<(ostream &os, Mint a) { return os << a.v; }",
      "    friend istream &operator>>(istream &is, Mint &a) { long long x; is >> x; a = Mint(x); return is; }",
      "};",
      "using mint = Mint<",
    }),
    i(1, "998244353"),
    t(">;"),
  }),

  -- KMP
  s("kmp", {
    t({
      "vector<int> kmp(const string &s) {",
      "    int n = s.size();",
      "    vector<int> pi(n);",
      "    for (int i = 1; i < n; i++) {",
      "        int j = pi[i - 1];",
      "        while (j && s[i] != s[j]) j = pi[j - 1];",
      "        if (s[i] == s[j]) j++;",
      "        pi[i] = j;",
      "    }",
      "    return pi;",
      "}",
    }),
  }),

  -- Z-function
  s("zfunc", {
    t({
      "vector<int> zfunc(const string &s) {",
      "    int n = s.size();",
      "    vector<int> z(n);",
      "    for (int i = 1, l = 0, r = 0; i < n; i++) {",
      "        if (i <= r) z[i] = min(r - i + 1, z[i - l]);",
      "        while (i + z[i] < n && s[z[i]] == s[i + z[i]]) z[i]++;",
      "        if (i + z[i] - 1 > r) l = i, r = i + z[i] - 1;",
      "    }",
      "    return z;",
      "}",
    }),
  }),

  -- Linear sieve
  s("sieve", {
    t({
      "vector<int> sieve(int n) {",
      "    vector<int> minp(n + 1), primes;",
      "    for (int i = 2; i <= n; i++) {",
      "        if (!minp[i]) minp[i] = i, primes.push_back(i);",
      "        for (int p : primes) {",
      "            if (p > minp[i] || i * p > n) break;",
      "            minp[i * p] = p;",
      "        }",
      "    }",
      "    return minp;",
      "}",
    }),
  }),

  -- LCA (binary lifting)
  s("lca", {
    t({
      "struct LCA {",
      "    vector<vector<int>> up;",
      "    vector<int> depth;",
      "    int LOG;",
      "    LCA(const vector<vector<int>> &g, int root = 0) {",
      "        int n = g.size();",
      "        LOG = __lg(n) + 1;",
      "        up.assign(n, vector<int>(LOG));",
      "        depth.assign(n, 0);",
      "        auto dfs = [&](auto &&self, int u, int p) -> void {",
      "            up[u][0] = p;",
      "            for (int j = 1; j < LOG; j++)",
      "                up[u][j] = up[up[u][j - 1]][j - 1];",
      "            for (int v : g[u]) if (v != p) {",
      "                depth[v] = depth[u] + 1;",
      "                self(self, v, u);",
      "            }",
      "        };",
      "        dfs(dfs, root, root);",
      "    }",
      "    int lift(int u, int k) {",
      "        for (int j = 0; j < LOG; j++) if (k >> j & 1) u = up[u][j];",
      "        return u;",
      "    }",
      "    int lca(int u, int v) {",
      "        if (depth[u] < depth[v]) swap(u, v);",
      "        u = lift(u, depth[u] - depth[v]);",
      "        if (u == v) return u;",
      "        for (int j = LOG - 1; j >= 0; j--)",
      "            if (up[u][j] != up[v][j])",
      "                u = up[u][j], v = up[v][j];",
      "        return up[u][0];",
      "    }",
      "    int dist(int u, int v) { return depth[u] + depth[v] - 2 * depth[lca(u, v)]; }",
      "};",
    }),
  }),

  -- Dinic max flow (jiangly style)
  s("dinic", {
    t({
      "struct Dinic {",
      "    struct Edge { int v, rev; i64 cap; };",
      "    vector<vector<Edge>> g;",
      "    vector<int> level, iter;",
      "    Dinic(int n) : g(n), level(n), iter(n) {}",
      "    void add(int u, int v, i64 cap) {",
      "        g[u].push_back({v, (int)g[v].size(), cap});",
      "        g[v].push_back({u, (int)g[u].size() - 1, 0});",
      "    }",
      "    void bfs(int s) {",
      "        fill(level.begin(), level.end(), -1);",
      "        queue<int> q;",
      "        level[s] = 0, q.push(s);",
      "        while (!q.empty()) {",
      "            int u = q.front(); q.pop();",
      "            for (auto &e : g[u]) if (e.cap && level[e.v] == -1) {",
      "                level[e.v] = level[u] + 1;",
      "                q.push(e.v);",
      "            }",
      "        }",
      "    }",
      "    i64 dfs(int u, int t, i64 f) {",
      "        if (u == t) return f;",
      "        for (int &i = iter[u]; i < (int)g[u].size(); i++) {",
      "            auto &e = g[u][i];",
      "            if (e.cap && level[u] < level[e.v]) {",
      "                i64 d = dfs(e.v, t, min(f, e.cap));",
      "                if (d) { e.cap -= d; g[e.v][e.rev].cap += d; return d; }",
      "            }",
      "        }",
      "        return 0;",
      "    }",
      "    i64 flow(int s, int t) {",
      "        i64 f = 0;",
      "        while (bfs(s), level[t] != -1) {",
      "            fill(iter.begin(), iter.end(), 0);",
      "            while (i64 d = dfs(s, t, 1e18)) f += d;",
      "        }",
      "        return f;",
      "    }",
      "};",
    }),
  }),

  -- SCC (jiangly style)
  s("scc", {
    t({
      "struct SCC {",
      "    vector<vector<int>> g;",
      "    vector<int> dfn, low, bel;",
      "    vector<int> stk;",
      "    int cur, cnt;",
      "    SCC(int n) : g(n), dfn(n, -1), low(n), bel(n, -1) { cur = cnt = 0; }",
      "    void add(int u, int v) { g[u].push_back(v); }",
      "    void dfs(int u) {",
      "        dfn[u] = low[u] = cur++;",
      "        stk.push_back(u);",
      "        for (int v : g[u]) {",
      "            if (dfn[v] == -1) dfs(v), low[u] = min(low[u], low[v]);",
      "            else if (bel[v] == -1) low[u] = min(low[u], dfn[v]);",
      "        }",
      "        if (dfn[u] == low[u]) {",
      "            int v;",
      "            do { v = stk.back(); stk.pop_back(); bel[v] = cnt; } while (v != u);",
      "            cnt++;",
      "        }",
      "    }",
      "    vector<int> work() {",
      "        for (int i = 0; i < (int)g.size(); i++) if (dfn[i] == -1) dfs(i);",
      "        return bel;",
      "    }",
      "};",
    }),
  }),

  -- 2-SAT (jiangly style)
  s("2sat", {
    t({
      "struct TwoSat {",
      "    vector<vector<int>> g;",
      "    vector<int> bel;",
      "    TwoSat(int n) : g(2 * n) {}",
      "    void add(int u, bool f, int v, bool gv) {",
      "        g[2 * u + !f].push_back(2 * v + gv);",
      "        g[2 * v + !gv].push_back(2 * u + f);",
      "    }",
      "    bool work() {",
      "        int n = g.size();",
      "        vector<int> dfn(n, -1), low(n);",
      "        vector<int> stk;",
      "        bel.assign(n, -1);",
      "        int cur = 0, cnt = 0;",
      "        auto dfs = [&](auto &&self, int u) -> void {",
      "            dfn[u] = low[u] = cur++;",
      "            stk.push_back(u);",
      "            for (int v : g[u]) {",
      "                if (dfn[v] == -1) self(self, v), low[u] = min(low[u], low[v]);",
      "                else if (bel[v] == -1) low[u] = min(low[u], dfn[v]);",
      "            }",
      "            if (dfn[u] == low[u]) {",
      "                int v;",
      "                do { v = stk.back(); stk.pop_back(); bel[v] = cnt; } while (v != u);",
      "                cnt++;",
      "            }",
      "        };",
      "        for (int i = 0; i < n; i++) if (dfn[i] == -1) dfs(dfs, i);",
      "        for (int i = 0; i < n / 2; i++) if (bel[2 * i] == bel[2 * i + 1]) return false;",
      "        return true;",
      "    }",
      "};",
    }),
  }),

  -- HLD (jiangly style)
  s("hld", {
    t({
      "struct HLD {",
      "    vector<int> parent, depth, siz, top, in, seq;",
      "    int cur;",
      "    HLD(const vector<vector<int>> &g, int root = 0) {",
      "        int n = g.size();",
      "        parent.resize(n); depth.resize(n); siz.resize(n);",
      "        top.resize(n); in.resize(n); seq.resize(n);",
      "        cur = 0;",
      "        auto dfs1 = [&](auto &&self, int u, int p) -> void {",
      "            parent[u] = p; siz[u] = 1;",
      "            for (int &v : g[u]) if (v != p) {",
      "                depth[v] = depth[u] + 1;",
      "                self(self, v, u);",
      "                siz[u] += siz[v];",
      "                if (siz[v] > siz[g[u][0]] || g[u][0] == p) swap(v, g[u][0]);",
      "            }",
      "        };",
      "        auto dfs2 = [&](auto &&self, int u) -> void {",
      "            in[u] = cur++; seq[in[u]] = u;",
      "            for (int v : g[u]) if (v != parent[u]) {",
      "                top[v] = v == g[u][0] ? top[u] : v;",
      "                self(self, v);",
      "            }",
      "        };",
      "        dfs1(dfs1, root, -1);",
      "        top[root] = root;",
      "        dfs2(dfs2, root);",
      "    }",
      "    int lca(int u, int v) {",
      "        while (top[u] != top[v]) {",
      "            if (depth[top[u]] > depth[top[v]]) swap(u, v);",
      "            v = parent[top[v]];",
      "        }",
      "        return depth[u] < depth[v] ? u : v;",
      "    }",
      "};",
    }),
  }),

  -- PBDS ordered set
  s("pbds", {
    t({
      "#include <ext/pb_ds/assoc_container.hpp>",
      "#include <ext/pb_ds/tree_policy.hpp>",
      "using namespace __gnu_pbds;",
      "template <typename T>",
      "using ordered_set = tree<T, null_type, less<T>, rb_tree_tag, tree_order_statistics_node_update>;",
    }),
  }),

  -- RNG
  s("rng", {
    t({
      "mt19937 rng(chrono::steady_clock::now().time_since_epoch().count());",
      "int randint(int l, int r) { return uniform_int_distribution<int>(l, r)(rng); }",
    }),
  }),

  -- chmin/chmax
  s("ch", {
    t({
      "template <typename T> bool ckmin(T &a, const T &b) { return b < a ? a = b, 1 : 0; }",
      "template <typename T> bool ckmax(T &a, const T &b) { return a < b ? a = b, 1 : 0; }",
    }),
  }),
})
