local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

ls.add_snippets("cuda", {
    s("!cu", {
        t({
            "#include <stdio.h>",
            "#include <cuda_runtime.h>",
            "",
            "#define SIZE (2048*2048)",
            "#define THREADS_PER_BLOCK 512",
            "",
            "__global__ void kernel(const float* A, const float* B, float* C, int N) {",
            "    // kernel code here",
            "}",
            "",
            "int main() {",
            "    size_t size = SIZE * sizeof(float);",
            "",
            "    // Host memory",
            "    float *h_A = (float*)malloc(size);",
            "    float *h_B = (float*)malloc(size);",
            "    float *h_C = (float*)malloc(size);",
            "",
            "    // Init host data",
            "    for (int i = 0; i < SIZE; i++) {",
            "        h_A[i] = 1.0f;",
            "        h_B[i] = 2.0f;",
            "    }",
            "",
            "    // Device memory",
            "    float *d_A, *d_B, *d_C;",
            "    cudaMalloc((void**)&d_A, size);",
            "    cudaMalloc((void**)&d_B, size);",
            "    cudaMalloc((void**)&d_C, size);",
            "",
            "    cudaMemcpy(d_A, h_A, size, cudaMemcpyHostToDevice);",
            "    cudaMemcpy(d_B, h_B, size, cudaMemcpyHostToDevice);",
            "",
            "    // Kernel launch",
            "    int blocksPerGrid = (SIZE + THREADS_PER_BLOCK - 1) / THREADS_PER_BLOCK;",
            "    kernel<<<blocksPerGrid, THREADS_PER_BLOCK>>>(d_A, d_B, d_C, SIZE);",
            "    cudaDeviceSynchronize();",
            "",
            "    cudaMemcpy(h_C, d_C, size, cudaMemcpyDeviceToHost);",
            "",
            "    // Check result",
            "    for (int i = 0; i < 10; i++) {",
            "        printf(\"C[%d] = %f\\n\", i, h_C[i]);",
            "    }",
            "",
            "    // Free",
            "    cudaFree(d_A);",
            "    cudaFree(d_B);",
            "    cudaFree(d_C);",
            "    free(h_A);",
            "    free(h_B);",
            "    free(h_C);",
            "",
            "    return 0;",
            "}",
        }),
    }),
})

